[package]
name = "elden-ring-windowed-hdr"
version = "1.0.0"
edition = "2024"
authors = ["Luna (a492219408)"]
license = "MIT"
description = "Enable Elden Ring's native HDR rendering in borderless and windowed modes through ModEngine3"
publish = false

[lib]
name = "EldenRingWindowedHDR"
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "s"
panic = "abort"
strip = "symbols"
